function opentarget(){
  var args=opentarget.arguments;
  if (args[0] != "#")
  {
      window.open(args[0]);
  }
}
document.write("<table width=768 border=0 cellspacing=0 cellpadding=0 align=center>");
document.write("  <tr> ");
document.write("    <td background=http://211.95.129.162/images/unicom_index_bg_001.gif height=36 width=573> ");
document.write("      <table width=548 border=0 cellspacing=0 cellpadding=0>");
document.write("        <tr> ");
document.write("          <td><a href=http://211.95.129.162/index.jsp target=_top><img src=http://211.95.129.162/images/unicom_index_img_023.gif width=78 height=36 border=0></a></td>");
document.write("          <td><a href=http://211.95.129.162/business/index.jsp target=_top><img src=http://211.95.129.162/images/unicom_index_img_001.gif width=78 height=36 border=0></a></td>");
document.write("          <td><a href=http://211.95.129.162/brand/index.jsp target=_top><img src=http://211.95.129.162/images/unicom_index_img_002.gif width=78 height=36 border=0></a></td>");
document.write("          <td><a href=http://211.95.129.162/service/index.htm target=_top><img src=http://211.95.129.162/images/unicom_index_img_003.gif width=78 height=36 border=0></a></td>");
document.write("          <td><a href=http://211.95.129.162/terminal/index.jsp target=_top><img src=http://211.95.129.162/images/unicom_index_img_004.gif width=78 height=36 border=0></a></td>");
document.write("          <td><a href=http://211.95.129.162/local/index.jsp target=_top><img src=http://211.95.129.162/images/unicom_index_img_005.gif width=78 height=36 border=0></a></td>");
document.write("          <td><a href=http://211.95.129.162/about/index.jsp target=_top><img src=http://211.95.129.162/images/unicom_index_img_006.gif width=100 height=36 border=0></a></td>");
document.write("        </tr>");
document.write("      </table>");
document.write("    </td>");
document.write("    <td background=http://211.95.129.162/images/unicom_index_bg_001.gif height=36 width=195> ");
document.write("      <table width=200 border=0 cellspacing=0 cellpadding=0>");
document.write("        <tr> ");
document.write("          <td align=right width=206> ");
document.write("            <select name=select onChange=opentarget(this.options[selectedIndex].value)>");
document.write("              <option value=#>--联通网站友情连接--</option>");
document.write("              <option value=http://www.chinaunicom.com>-------总部-------</option>");
document.write("              <option value=http://www.bj.chinaunicom.com>-------北京-------</option>");
document.write("              <option value=http://www.tj.chinaunicom.com>-------天津-------</option>");
document.write("              <option value=http://www.he.chinaunicom.com>-------河北-------</option>");
document.write("              <option value=http://www.nm.chinaunicom.com>------内蒙古------</option>");
document.write("              <option value=http://www.sx.chinaunicom.com>-------山西-------</option>");
document.write("              <option value=http://www.jl.chinaunicom.com>-------吉林-------</option>");
document.write("              <option value=http://www.hl.chinaunicom.com>------黑龙江------</option>");
document.write("              <option value=http://www.sh.chinaunicom.com>-------上海-------</option>");
document.write("              <option value=http://www.js.chinaunicom.com>-------江苏-------</option>");
document.write("              <option value=http://www.sd.chinaunicom.com>-------山东-------</option>");
document.write("              <option value=http://www.ah.chinaunicom.com>-------安徽-------</option>");
document.write("              <option value=http://www.zj.chinaunicom.com>-------浙江-------</option>");
document.write("              <option value=http://www.hj.chinaunicom.com>-------福建-------</option>");
document.write("              <option value=http://www.jx.chinaunicom.com>-------江西-------</option>");
document.write("              <option value=http://www.hb.chinaunicom.com>-------湖北-------</option>");
document.write("              <option value=http://www.ha.chinaunicom.com>-------河南-------</option>");
document.write("              <option value=http://www.hn.chinaunicom.com>-------湖南-------</option>");
document.write("              <option value=http://www.gd.chinaunicom.com>-------广东-------</option>");
document.write("              <option value=http://www.gx.chinaunicom.com>-------广西-------</option>");
document.write("              <option value=http://www.hn.chinaunicom.com>-------海南-------</option>");
document.write("              <option value=http://www.cq.chinaunicom.com>-------重庆-------</option>");
document.write("              <option value=http://www.gz.chinaunicom.com>-------贵州-------</option>");
document.write("              <option value=http://www.yn.chinaunicom.com>-------云南-------</option>");
document.write("              <option value=http://vwww.sn.chinaunicom.com>-------陕西-------</option>");
document.write("              <option value=http://www.gs.chinaunicom.com>-------甘肃-------</option>");
document.write("              <option value=http://www.qh.chinaunicom.com>-------青海-------</option>");
document.write("              <option value=http://www.nx.chinaunicom.com>-------宁夏-------</option>");
document.write("              <option vvalue=http://www.xj.chinaunicom.com>-------新疆-------</option>");
document.write("              <option value=http://www.xz.chinaunicom.com>-------西藏-------</option>");
document.write("            </select>");
document.write("          </td>");
document.write("          <td align=right width=14>&nbsp;</td>");
document.write("        </tr>");
document.write("      </table>");
document.write("    </td>");
document.write("  </tr>");
document.write("  <tr> ");
document.write("    <td height=2 colspan=2></td>");
document.write("  </tr>");
document.write("</table>");